# Generated by Django 2.2 on 2019-12-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photography',
            old_name='author',
            new_name='photo_author',
        ),
    ]
