# Generated by Django 2.2 on 2019-12-14 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_auto_20191214_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='photo_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to=settings.AUTH_USER_MODEL, verbose_name='Автор фотографии'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('like_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='Автор лайка')),
                ('photography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='webapp.Photography', verbose_name='Фотография')),
            ],
        ),
    ]
